// SafePoll contract deployed on Sepolia (copied from deployments/sepolia/SafePoll.json)
export const CONTRACT_ADDRESS = '0x88474C7e2f11F9Ca90f8b58c5773e1Ce1F55408e';

export const CONTRACT_ABI = [
  { "inputs": [], "name": "HandlesAlreadySavedForRequestID", "type": "error" },
  { "inputs": [], "name": "InvalidKMSSignatures", "type": "error" },
  { "inputs": [], "name": "NoHandleFoundForRequestID", "type": "error" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "requestID", "type": "uint256" } ], "name": "DecryptionFulfilled", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "surveyId", "type": "uint256" } ], "name": "ResultsDecrypted", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "creator", "type": "address" }, { "indexed": false, "internalType": "string", "name": "title", "type": "string" } ], "name": "SurveyCreated", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "surveyId", "type": "uint256" } ], "name": "SurveyEnded", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "voter", "type": "address" } ], "name": "VoteSubmitted", "type": "event" },
  { "inputs": [ { "internalType": "string", "name": "title", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "string[]", "name": "questionTexts", "type": "string[]" }, { "internalType": "string[][]", "name": "questionOptions", "type": "string[][]" } ], "name": "createSurvey", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "", "type": "uint256" }, { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "decryptedResults", "outputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "internalType": "uint256", "name": "questionIndex", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "requestId", "type": "uint256" }, { "internalType": "bytes", "name": "cleartexts", "type": "bytes" }, { "internalType": "bytes", "name": "decryptionProof", "type": "bytes" } ], "name": "decryptionCallback", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" } ], "name": "endSurvey", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "internalType": "uint256", "name": "questionIndex", "type": "uint256" }, { "internalType": "uint256", "name": "optionIndex", "type": "uint256" } ], "name": "getEncryptedOptionCount", "outputs": [ { "internalType": "euint32", "name": "", "type": "bytes32" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "internalType": "uint256", "name": "questionIndex", "type": "uint256" } ], "name": "getQuestion", "outputs": [ { "internalType": "string", "name": "text", "type": "string" }, { "internalType": "string[]", "name": "options", "type": "string[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" } ], "name": "getSurveyInfo", "outputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "title", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "address", "name": "creator", "type": "address" }, { "internalType": "bool", "name": "isActive", "type": "bool" }, { "internalType": "bool", "name": "resultsDecrypted", "type": "bool" }, { "internalType": "uint256", "name": "questionCount", "type": "uint256" }, { "internalType": "uint256", "name": "totalVotes", "type": "uint256" }, { "internalType": "uint256", "name": "createdAt", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "getTotalSurveys", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "internalType": "address", "name": "voter", "type": "address" } ], "name": "hasUserVoted", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "protocolId", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "pure", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" } ], "name": "requestDecryption", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "surveyId", "type": "uint256" }, { "internalType": "externalEuint32[]", "name": "encryptedVotes", "type": "bytes32[]" }, { "internalType": "bytes", "name": "inputProof", "type": "bytes" } ], "name": "submitVotes", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "name": "surveys", "outputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "string", "name": "title", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "address", "name": "creator", "type": "address" }, { "internalType": "bool", "name": "isActive", "type": "bool" }, { "internalType": "bool", "name": "resultsDecrypted", "type": "bool" }, { "internalType": "uint256", "name": "questionCount", "type": "uint256" }, { "internalType": "uint256", "name": "totalVotes", "type": "uint256" }, { "internalType": "uint256", "name": "createdAt", "type": "uint256" } ], "stateMutability": "view", "type": "function" }
] as const;

